name: 'ipeds_dbt'
version: '1.0.0'
config-version: 2

# Which profile in profiles.yml to use
profile: 'ipeds_dbt'

# Paths
model-paths: ['models']
seed-paths: ['seeds']
snapshot-paths: ['snapshots']
test-paths: ['tests']
analysis-paths: ['analyses']
macro-paths: ['macros']

vars:
  grad_years: [2020, 2021, 2022, 2023]

# Where dbt puts compiled SQL + artifacts
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ipeds_dbt:
    +materialized: table

    staging:
      +schema: STAGING
    dimensions:
      +schema: DIMENSIONS
    marts:
      +schema: MARTS

# Configure seed files (lookup/code tables)
seeds:
  ipeds_dbt:
    +schema: SEEDS
    +quote_columns: false

    chrtstat_code:
      column_types:
        code: varchar
        label: varchar
    cohort_code:
      column_types:
        code: varchar
        label: varchar
    grtype_code:
      column_types:
        code: varchar
        label: varchar
    line_code:
      column_types:
        code: varchar
        label: varchar
    section_code:
      column_types:
        code: varchar
        label: varchar
    varlist_columns:
      column_types:
        varname: varchar
        vartitle: varchar
